import { mkdir } from "node:fs/promises";
import { basename, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile, DEFAULT_OPTIONS } from "json-schema-to-typescript";

/** v2.5.5 */
const kDenoVersion = "367ecdd0360e935de0454c70e0018be61c02904e";
const kBaseURL =
  `https://raw.githubusercontent.com/denoland/deno/${kDenoVersion}/cli/schemas`;
const kConfigFileSchemaURL = `${kBaseURL}/config-file.v1.json`;
const kLintTagsSchemaURL = `${kBaseURL}/lint-tags.v1.json`;
const kLintRulesSchemaURL = `${kBaseURL}/lint-rules.v1.json`;

const kGeneratedDir = fileURLToPath(new URL("../generated", import.meta.url));
const kTmpDir = fileURLToPath(new URL("../tmp", import.meta.url));

async function download(url: URL) {
  const res = await fetch(url);
  await Deno.writeTextFile(
    join(
      kTmpDir,
      basename(url.pathname),
    ),
    await res.text(),
  );
}

async function downloadSchemaFiles() {
  await download(new URL(kConfigFileSchemaURL));
  await download(new URL(kLintTagsSchemaURL));
  await download(new URL(kLintRulesSchemaURL));
}

async function main() {
  await mkdir(kTmpDir, { recursive: true });
  await downloadSchemaFiles();
  const schemaFilename = basename(new URL(kConfigFileSchemaURL).pathname);
  const content = await compileFromFile(
    join(kTmpDir, schemaFilename),
    {
      ...DEFAULT_OPTIONS,
      bannerComment: `/**
 * This file was automatically generated by json-schema-to-typescript from the following files:
 * * ${kConfigFileSchemaURL}
 * * ${kLintTagsSchemaURL}
 * * ${kLintRulesSchemaURL}
 */`,
      cwd: kTmpDir,
    },
  );
  await Deno.writeTextFile(
    join(kGeneratedDir, replaceExtname(schemaFilename, ".ts")),
    content,
  );
}

function replaceExtname(filename: string, newExtname: `.${string}`): string {
  return removeSuffix(filename, extname(filename)) + newExtname;
}

function removeSuffix(s: string, suffix: string): string {
  if (suffix.length > 0 && s.endsWith(suffix)) {
    return s.slice(0, -suffix.length);
  } else {
    return s;
  }
}

if (import.meta.main) {
  main().catch((error) => {
    // deno-lint-ignore no-console -- This is a script file that is not provided to users.
    console.error(error);
    Deno.exit(1);
  });
}
