name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .deno-version)" >> $GITHUB_ENV
      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.deno-version', 'deno.lock') }}
      - name: Install deps
        run: deno install
      - name: Run linters
        run: |
          deno task check
      - name: Run tools:typegen task
        run: |
          deno task tools:typegen
          git diff --exit-code
      - name: Run tools:generate-rules-md task
        run: |
          deno task tools:generate-rules-md
          git diff --exit-code
      - name: Run tests
        run: deno task test
      - name: Run e2e tests
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          NO_COLOR=1 deno task test:e2e 2>> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: deno publish --dry-run
        run:
          deno publish --dry-run
